/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.org.centro8.curso.java.gui;

import ar.org.centro8.curso.java.entities.Categoria;
import ar.org.centro8.curso.java.entities.Venta;
import ar.org.centro8.curso.java.repositories.interfaces.I_ProductoR;
import ar.org.centro8.curso.java.repositories.interfaces.I_VentaR;
import ar.org.centro8.curso.java.repositories.interfaces.I_CategoriaR;
import ar.org.centro8.curso.java.repositories.jpa.ProductoR;
import ar.org.centro8.curso.java.repositories.jpa.VentaR;
import ar.org.centro8.curso.java.repositories.jpa.CategoriaR;
import ar.org.centro8.curso.java.utils.swing.Table;
import java.awt.Color;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Venta venta = new Venta(new Date(),10, 0, 650, "Garantia 1 mes", cl.getByCodigo(2), us.getByCodigo(3), prod.getByCodigo(65090));
        vta.save(venta);
  @author Dv4
 * 
 */
 
public class FormPrincipalMV extends javax.swing.JFrame {

    private I_ProductoR pr;
    private I_VentaR vr;
     private I_CategoriaR cr;
    
    EntityManagerFactory emf=Persistence.createEntityManagerFactory("JPAPUMV");
    EntityManager em=emf.createEntityManager();
    public FormPrincipalMV() {
        initComponents();
        
          pr = new ProductoR(em);
          vr = new VentaR(em);
          cr = new CategoriaR(em);
          
          cargarVentas();
          cargarCategorias();
          
          /*Diseño*/
          
          panelVentas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelVentas = new javax.swing.JPanel();
        lblSetVentsBuscar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblSetNuevaVenta = new javax.swing.JLabel();
        lblSetVentasTodas = new javax.swing.JLabel();
        jPMVentas = new javax.swing.JPanel();
        lblVentas = new javax.swing.JLabel();
        JpSecciones = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtBuscarVenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtcantidad1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegCat = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lblcantidadCategorias = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        BtnSaveCategoria = new javax.swing.JButton();
        txtBuscarCategoria = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(20, 114, 191));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(246, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("IMEGA");

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("La tecnologia al alcance de tus manos");

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(204, 255, 255));

        panelVentas.setBackground(new java.awt.Color(246, 255, 255));
        panelVentas.setForeground(new java.awt.Color(204, 255, 255));
        panelVentas.setPreferredSize(new java.awt.Dimension(190, 80));
        panelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetVentsBuscar.setBackground(new java.awt.Color(255, 255, 255));
        lblSetVentsBuscar.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        lblSetVentsBuscar.setForeground(new java.awt.Color(0, 51, 51));
        lblSetVentsBuscar.setText("- Buscar");
        lblSetVentsBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSetVentsBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSetVentsBuscarMouseMoved(evt);
            }
        });
        lblSetVentsBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetVentsBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSetVentsBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSetVentsBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSetVentsBuscarMousePressed(evt);
            }
        });
        panelVentas.add(lblSetVentsBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(20, 114, 152));
        jSeparator2.setForeground(new java.awt.Color(153, 255, 255));
        panelVentas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 21, 190, 2));

        jSeparator4.setBackground(new java.awt.Color(20, 114, 152));
        jSeparator4.setForeground(new java.awt.Color(153, 255, 255));
        panelVentas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 45, 190, 2));

        lblSetNuevaVenta.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNuevaVenta.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        lblSetNuevaVenta.setForeground(new java.awt.Color(0, 51, 51));
        lblSetNuevaVenta.setText("- Nueva Venta");
        lblSetNuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSetNuevaVenta.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSetNuevaVentaMouseMoved(evt);
            }
        });
        lblSetNuevaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetNuevaVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSetNuevaVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSetNuevaVentaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSetNuevaVentaMousePressed(evt);
            }
        });
        panelVentas.add(lblSetNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2, -1, -1));

        lblSetVentasTodas.setBackground(new java.awt.Color(255, 255, 255));
        lblSetVentasTodas.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        lblSetVentasTodas.setForeground(new java.awt.Color(0, 51, 51));
        lblSetVentasTodas.setText("- Todas las ventas");
        lblSetVentasTodas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSetVentasTodas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSetVentasTodasMouseMoved(evt);
            }
        });
        lblSetVentasTodas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetVentasTodasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSetVentasTodasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSetVentasTodasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSetVentasTodasMousePressed(evt);
            }
        });
        panelVentas.add(lblSetVentasTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jPMVentas.setBackground(new java.awt.Color(20, 114, 191));
        jPMVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPMVentas.setPreferredSize(new java.awt.Dimension(100, 30));
        jPMVentas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPMVentasMouseMoved(evt);
            }
        });
        jPMVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPMVentasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPMVentasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPMVentasMousePressed(evt);
            }
        });

        lblVentas.setBackground(new java.awt.Color(20, 114, 191));
        lblVentas.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(255, 255, 255));
        lblVentas.setText("+Ventas");
        lblVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVentas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblVentasMouseMoved(evt);
            }
        });
        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVentasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPMVentasLayout = new javax.swing.GroupLayout(jPMVentas);
        jPMVentas.setLayout(jPMVentasLayout);
        jPMVentasLayout.setHorizontalGroup(
            jPMVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentas)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPMVentasLayout.setVerticalGroup(
            jPMVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPMVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPMVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(panelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        JpSecciones.setBackground(new java.awt.Color(204, 204, 204));

        txtBuscarVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscarVenta.setBorder(null);
        txtBuscarVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarVentaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarVentaKeyReleased(evt);
            }
        });

        jLabel4.setText("Search");

        tblVentas.setBackground(new java.awt.Color(246, 255, 255));
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVentas.setRowHeight(25);
        jScrollPane1.setViewportView(tblVentas);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Fecha:");

        lblFechaVenta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblFechaVenta.setText("20/06/2019");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Cliente:");

        txtCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtCliente.setBorder(null);
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Descuento %:");

        txtDescuento.setBackground(new java.awt.Color(204, 204, 204));
        txtDescuento.setBorder(null);
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Total:");

        txtTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtTotal.setBorder(null);
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Vendedor:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Cantidad:");

        txtcantidad1.setBackground(new java.awt.Color(204, 204, 204));
        txtcantidad1.setBorder(null);
        txtcantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidad1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidad1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator3)
                            .addComponent(txtBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCliente))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, 0, 127, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(txtcantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(522, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblFechaVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(txtcantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Ventas", jPanel3);

        tblRegCat.setBackground(new java.awt.Color(0, 102, 102));
        tblRegCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRegCat.setToolTipText("Ingrese Categoria");
        tblRegCat.setRowHeight(25);
        tblRegCat.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblRegCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblRegCatKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblRegCat);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Total :");

        lblcantidadCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcantidadCategorias.setText("10");

        tblCategorias.setBackground(new java.awt.Color(246, 255, 255));
        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCategorias.setRowHeight(25);
        jScrollPane3.setViewportView(tblCategorias);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Registro de Categorias");

        BtnSaveCategoria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BtnSaveCategoria.setText("Save");
        BtnSaveCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveCategoriaActionPerformed(evt);
            }
        });

        txtBuscarCategoria.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscarCategoria.setBorder(null);
        txtBuscarCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarCategoriaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarCategoriaKeyReleased(evt);
            }
        });

        jLabel13.setText("Search");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 0));
        jLabel14.setText("Delete");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(236, 236, 236))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblcantidadCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BtnSaveCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator7)
                                            .addComponent(txtBuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(9, 9, 9)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(BtnSaveCategoria)
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(1, 1, 1)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblcantidadCategorias))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Categorias", jPanel5);

        tblProveedores.setBackground(new java.awt.Color(246, 255, 255));
        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProveedores.setRowHeight(25);
        jScrollPane5.setViewportView(tblProveedores);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedor", jPanel4);

        javax.swing.GroupLayout JpSeccionesLayout = new javax.swing.GroupLayout(JpSecciones);
        JpSecciones.setLayout(JpSeccionesLayout);
        JpSeccionesLayout.setHorizontalGroup(
            JpSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        JpSeccionesLayout.setVerticalGroup(
            JpSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpSecciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSetVentsBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentsBuscarMouseMoved
        lblSetVentsBuscar.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblSetVentsBuscarMouseMoved

    private void lblSetVentsBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentsBuscarMouseClicked
        
    }//GEN-LAST:event_lblSetVentsBuscarMouseClicked

    private void lblSetVentsBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentsBuscarMouseEntered

    }//GEN-LAST:event_lblSetVentsBuscarMouseEntered

    private void lblSetVentsBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentsBuscarMouseExited
        lblSetVentsBuscar.setForeground(new Color(0,51,51));
    }//GEN-LAST:event_lblSetVentsBuscarMouseExited

    private void lblSetVentsBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentsBuscarMousePressed
       // lblSetVentsBuscar.setForeground(Color.darkGray);
    }//GEN-LAST:event_lblSetVentsBuscarMousePressed

    private void lblVentasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseMoved

    }//GEN-LAST:event_lblVentasMouseMoved

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked

        if(lblVentas.getText().equals("+Ventas")){
            panelVentas.setVisible(true);
            lblVentas.setText("-Ventas");
            jPMVentas.setBackground(new Color(21,109,139));
        }
        else{
            if (lblVentas.getText().equals("-Ventas")){
                panelVentas.setVisible(false);
                lblVentas.setText("+Ventas");
                jPMVentas.setBackground(new Color(20,114,191));

            }
        }
    }//GEN-LAST:event_lblVentasMouseClicked

    private void lblVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseExited

    }//GEN-LAST:event_lblVentasMouseExited

    private void jPMVentasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMVentasMouseMoved
        jPMVentas.setBackground(new Color(21,109,139));
        // TODO add your handling code here:100 54
    }//GEN-LAST:event_jPMVentasMouseMoved

    private void jPMVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMVentasMouseClicked

        if(lblVentas.getText().equals("+Ventas")){
            panelVentas.setVisible(true);
            lblVentas.setText("-Ventas");
            jPMVentas.setBackground(new Color(21,109,139));
        }
        else{
            if (lblVentas.getText().equals("-Ventas")){
                panelVentas.setVisible(false);
                lblVentas.setText("+Ventas");
                jPMVentas.setBackground(new Color(20,114,191));

            }
        }

    }//GEN-LAST:event_jPMVentasMouseClicked

    private void jPMVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMVentasMouseExited
        if (lblVentas.getText().equals("+Ventas")){
            jPMVentas.setBackground(new Color(20,114,191));

        }

    }//GEN-LAST:event_jPMVentasMouseExited

    private void jPMVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMVentasMousePressed
        jPMVentas.setBackground(new Color(2,128,231,220));
    }//GEN-LAST:event_jPMVentasMousePressed

    private void lblSetNuevaVentaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetNuevaVentaMouseMoved
         lblSetNuevaVenta.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblSetNuevaVentaMouseMoved

    private void lblSetNuevaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetNuevaVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSetNuevaVentaMouseClicked

    private void lblSetNuevaVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetNuevaVentaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSetNuevaVentaMouseEntered

    private void lblSetNuevaVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetNuevaVentaMouseExited
       lblSetNuevaVenta.setForeground(new Color(0,51,51));
    }//GEN-LAST:event_lblSetNuevaVentaMouseExited

    private void lblSetNuevaVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetNuevaVentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSetNuevaVentaMousePressed

    private void lblSetVentasTodasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentasTodasMouseMoved
lblSetVentasTodas.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblSetVentasTodasMouseMoved

    private void lblSetVentasTodasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentasTodasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSetVentasTodasMouseClicked

    private void lblSetVentasTodasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentasTodasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSetVentasTodasMouseEntered

    private void lblSetVentasTodasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentasTodasMouseExited
        lblSetVentasTodas.setForeground(new Color(0,51,51));
    }//GEN-LAST:event_lblSetVentasTodasMouseExited

    private void lblSetVentasTodasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetVentasTodasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSetVentasTodasMousePressed

    private void txtBuscarVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarVentaKeyPressed
        
        
    }//GEN-LAST:event_txtBuscarVentaKeyPressed

    private void txtBuscarVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarVentaKeyReleased
        // Evento Buscar Curso
       /* int buscar = Integer.parseInt(txtBuscarVenta.getText());
        new Table<Venta>()
        .cargar(tblVentas,               
            vr.getById(buscar);*/
    }//GEN-LAST:event_txtBuscarVentaKeyReleased

    private void txtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteKeyPressed

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteKeyReleased

    private void txtDescuentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoKeyPressed

    private void txtDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoKeyReleased

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyPressed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyReleased

    private void txtcantidad1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidad1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidad1KeyPressed

    private void txtcantidad1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidad1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidad1KeyReleased

    private void BtnSaveCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveCategoriaActionPerformed
       SaveCategoria();       
    }//GEN-LAST:event_BtnSaveCategoriaActionPerformed

    private void tblRegCatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRegCatKeyPressed
       SaveCategoria();   
    }//GEN-LAST:event_tblRegCatKeyPressed

    private void txtBuscarCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCategoriaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCategoriaKeyPressed

    private void txtBuscarCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCategoriaKeyReleased
       new Table<Categoria>().
                cargar(tblCategorias, 
                        cr.getLikeNombre(txtBuscarCategoria.getText()));
    }//GEN-LAST:event_txtBuscarCategoriaKeyReleased

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
      DeleteCategoria();
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipalMV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipalMV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipalMV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipalMV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipalMV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSaveCategoria;
    private javax.swing.JPanel JpSecciones;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPMVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblSetNuevaVenta;
    private javax.swing.JLabel lblSetVentasTodas;
    private javax.swing.JLabel lblSetVentsBuscar;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JLabel lblcantidadCategorias;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTable tblRegCat;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtBuscarCategoria;
    private javax.swing.JTextField txtBuscarVenta;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtcantidad1;
    // End of variables declaration//GEN-END:variables
    private void cargarVentas() {
        new Table().cargar(tblVentas, vr.getAll());
      }


    
    /*CATEGORIAS*/
    private void cargarCategorias() {
        new Table().cargar(tblCategorias, cr.getAll());
    }
    private void SaveCategoria() {
        String cat=tblRegCat.getValueAt(0, 0) + "";
        Categoria categoria=new Categoria(cat);
            cr.save(categoria);
            cargarCategorias();
            tblRegCat.setValueAt("", 0,0);}

    private void DeleteCategoria() {
            // Evento Eliminar
        int fila = tblCategorias.getSelectedRow();
        if (fila == -1) {
            return;
        }
        Categoria categoria = new Categoria(
                Integer.parseInt(tblCategorias.getValueAt(fila, 0) + ""),
                tblCategorias.getValueAt(fila, 1) + ""
        );
        if (JOptionPane
                .showConfirmDialog(
                        this,
                        "Desea borrar el curso codigo:" + categoria.getId()) == 0) {
            cr.remove(categoria);
        }
        cargarCategorias(); 
    }

    }
